DISABLE_LINTERS:
  - TYPESCRIPT_STANDARD
  - REPOSITORY_KICS
  - JAVASCRIPT_STANDARD

DISABLE_ERRORS_LINTERS:
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - HTML_DJLINT
  - HTML_HTMLHINT

JSON_JSONLINT_FILTER_REGEX_EXCLUDE: "tsconfig.*\\.json"
